
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA INT IS LBRACKET LIST LPAREN NAME RBRACKET RECEIVE RPAREN SHOW STRINGstatement : NAME IS RECEIVE LPAREN STRING RPARENstatement : SHOW LPAREN DATA RPARENDATA : INT\n          | STRINGstatement : LBRACKET DATA RBRACKETstatement : NAME IS DATAstatement : NAME'
    
_lr_action_items = {'NAME':([0,],[2,]),'SHOW':([0,],[3,]),'LBRACKET':([0,],[4,]),'$end':([1,2,8,9,11,13,15,17,],[0,-7,-3,-4,-6,-5,-2,-1,]),'IS':([2,],[5,]),'LPAREN':([3,10,],[6,14,]),'INT':([4,5,6,],[8,8,8,]),'STRING':([4,5,6,14,],[9,9,9,16,]),'RECEIVE':([5,],[10,]),'RBRACKET':([7,8,9,],[13,-3,-4,]),'RPAREN':([8,9,12,16,],[-3,-4,15,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'DATA':([4,5,6,],[7,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME IS RECEIVE LPAREN STRING RPAREN','statement',6,'p_receive','temp.py',43),
  ('statement -> SHOW LPAREN DATA RPAREN','statement',4,'p_show','temp.py',48),
  ('DATA -> INT','DATA',1,'p_data','temp.py',53),
  ('DATA -> STRING','DATA',1,'p_data','temp.py',54),
  ('statement -> LBRACKET DATA RBRACKET','statement',3,'p_list','temp.py',59),
  ('statement -> NAME IS DATA','statement',3,'p_is','temp.py',64),
  ('statement -> NAME','statement',1,'p_variable','temp.py',69),
]
